In [7]:
import pandas as pd

In [3]:
df = pd.read_json(r"C:\Users\Lenovo\Documents\Web scraping\IMDB\Iphone15.json")
df

,Buyer_name,Rating,Review
0,Mousam Guha Roy,4,Very nice
1,Prithivi Boruah,5,Camera Quality Is Improved Loving It
2,Ajin V,5,High quality cameraüòç
3,Sheetla Prasad Maurya,4,Best mobile phoneCamera quality is very nice B...
4,mohit yadav,5,Nice ‚ù§Ô∏è
...,...,...,...
182,Abhishek Parmar,3,Battery is not good need to charger 3 times a ...
183,Aman Rana,5,Money worth it
184,Unknown 711,5,Everything is wow
185,Shinz PK,5,Good Performance.
186,Anjali Singh,5,Better